accounts/urls.py
from django.urls import path
from . import views as vs

app_name = 'accounts'
urlpatterns = [path('', vs.account_page, name='account-page')]

daily/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views as vs

app_name = 'main'
urlpatterns = [



    path('', vs.index, name='index'),
    path('create/', vs.create_note, name='create'),
    path('note_page/<str:serial_id>/', vs.note_page, name='note-page'),

]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class DailyNotes(models.Model):
    serial_number = models.AutoField(primary_key=True)
    user_owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    descriptions = models.TextField()
    note_image = models.ImageField(
        upload_to='images', default='image.jpg', blank=True, null=True)
    bacground_image = models.ImageField(
        upload_to='background', default='background.jpg',  blank=True, null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

main/forms.py
from django import forms
from.models import DailyNotes


class DailyNotesForm(forms.ModelForm):

    class Meta:
        model = DailyNotes
        fields = ['title', 'descriptions', 'note_image', 'bacground_image']

accounts/views.py
from django.shortcuts import render

# Create your views here.
def account_page(request):
    return render(request, 'accounts/accounts.html')

main/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .models import DailyNotes
from .forms import DailyNotesForm
# Create your views here.


@login_required(login_url='accounts/login/')
def index(request):
    daily_notes = DailyNotes.objects.filter(user_owner=request.user)
    context = {'daily_notes': daily_notes}
    return render(request, 'main/index.html', context)


@login_required(login_url='accounts/login/')
def create_note(request):
    if request.method == 'POST':
        form = DailyNotesForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user_owner = request.user
            form.save()
            return redirect('main:index')
    context = {'form': DailyNotesForm}
    return render(request, 'main/create.html', context)


@login_required(login_url='accounts/login/')
def note_page(request, serial_id):
    daily_notes = DailyNotes.objects.filter(user_owner=request.user)
    this_note = DailyNotes.objects.filter(serial_number=serial_id).first()
    context = {'this_note': this_note, 'daily_notes': daily_notes}
    return render(request, 'main/note_page.html', context)

accounts/templates/accounts/accounts.html
{% extends "base.html " %}

<!-- title block  -->
{% block title %} Accounts Page {% endblock title %}

<!-- content block  -->
{% block content %} {% endblock content %}

main/templates/components/card_note.html
<div class="p-4 md:w-1/3">
  <div
    class="h-full rounded-xl shadow-cla-pink bg-gradient-to-r from-fuchsia-50 to-pink-50 overflow-hidden"
  >
    <img
      class="lg:h-48 md:h-36 w-full object-cover object-center scale-110 transition-all duration-400 hover:scale-100"
      src="/media/{{note.bacground_image}}"
      alt="blog"
    />
    <div class="p-6">
      <!-- <h2
        class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1"
      >
        CATEGORY-1
      </h2> -->
      <h1 class="title-font text-lg font-medium text-gray-600 mb-3">
        {{note.title}}
      </h1>
      <p class="leading-relaxed mb-3">{{note.descriptions}}</p>
      <div class="flex items-center flex-wrap">
        <a
          href="{% url 'main:note-page' note.serial_number %}"
          class="bg-gradient-to-r from-fuchsia-300 to-pink-400 hover:scale-105 shadow-cla-blue px-4 py-1 rounded-lg"
        >
          View Note Page
        </a>
      </div>
    </div>
  </div>
</div>

main/templates/components/create_form.html
<!-- component -->
<div class="w-full bg-gray-800 h-screen">
  <div class="bg-gradient-to-b from-blue-800 to-blue-600 h-96"></div>
  <div class="max-w-5xl mx-auto px-6 sm:px-6 lg:px-8 mb-12">
    <div class="bg-gray-900 w-full shadow rounded p-8 sm:p-12 -mt-72">
      <p class="text-3xl font-bold leading-7 text-center text-white">
        Create Daily Note
      </p>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="md:flex items-center mt-12">
          <div class="w-full md:w-1/2 flex flex-col">
            <label class="font-semibold leading-none text-gray-300"
              >Title Daily Note</label
            >
            <input
              type="text"
              name="title"
              class="leading-none text-gray-50 p-3 focus:outline-none focus:border-blue-700 mt-4 border-0 bg-gray-800 rounded"
            />
          </div>
        </div>
        <div class="md:flex items-center mt-8">
          <div class="w-full flex flex-col">
            <label class="font-semibold leading-none text-gray-300"
              >Note Image</label
            >
            <input
              type="file"
              name="note_image"
              class="leading-none text-gray-50 p-3 focus:outline-none focus:border-blue-700 mt-4 border-0 bg-gray-800 rounded"
            />
          </div>
        </div>
        <div class="md:flex items-center mt-8">
          <div class="w-full flex flex-col">
            <label class="font-semibold leading-none text-gray-300"
              >Add a Background for Note
            </label>
            <input
              type="file"
              name="bacground_image"
              class="leading-none text-gray-50 p-3 focus:outline-none focus:border-blue-700 mt-4 border-0 bg-gray-800 rounded"
            />
          </div>
        </div>
        <div>
          <div class="w-full flex flex-col mt-8">
            <label class="font-semibold leading-none text-gray-300"
              >Add a Descriptions for Note</label
            >
            <textarea
              name="descriptions"
              type="text"
              class="h-40 text-base leading-none text-gray-50 p-3 focus:outline-none focus:border-blue-700 mt-4 bg-gray-800 border-0 rounded"
            ></textarea>
          </div>
        </div>
        <div class="flex items-center justify-center w-full">
          <button
            type="submit"
            class="mt-9 font-semibold leading-none text-white py-4 px-10 bg-blue-700 rounded hover:bg-blue-600 focus:ring-2 focus:ring-offset-2 focus:ring-blue-700 focus:outline-none"
          >
            Create Daily Note
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

main/templates/components/note_page_component.html
<!-- component -->
<div class="py-16 bg-white">
  <div class="container m-auto px-6 text-gray-600 md:px-12 xl:px-6">
    <div
      class="space-y-6 md:space-y-0 md:flex md:gap-6 lg:items-center lg:gap-12"
    >
      <div class="md:5/12 lg:w-5/12">
        <img
          src="/media/{{this_note.bacground_image}}"
          alt="image"
          loading="lazy"
          width=""
          height=""
        />
      </div>
      <div class="md:7/12 lg:w-6/12">
        <h2 class="text-2xl text-gray-900 font-bold md:text-4xl">
          {{this_note.title}}
        </h2>
        <p class="mt-6 text-gray-600">{{this_note.descriptions}}</p>

      </div>
    </div>
  </div>
</div>

main/templates/main/create.html
{% extends "base.html" %}

<!-- title block  -->
{% block title %} Create Daily Note {% endblock title %}

<!-- content block -->
{% block content %} {% include "components/create_form.html" %}
<!-- end content -->
{% endblock content %}

main/templates/main/index.html
{% extends "base.html" %}

<!-- title block  -->
{% block title %} Hello {% endblock title %}

<!-- content block -->
{% block content %} {% endblock content %}

main/templates/main/note_page.html
{% extends "base.html" %}

<!-- title block  -->
{% block title %} NotePage {% endblock title %}

<!-- content block -->
{% block content %}
<!-- for loop -->
{% include "components/note_page_component.html" %}
<!-- end loop -->
{% include "main/view_note.html" %}

<!-- end content -->
{% endblock content %}

main/templates/main/view_note.html
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap -m-4">
      {% for note in daily_notes %}
      <!-- include card note -->
      {% include "components/card_note.html" %}
      <!-- end for  -->
      {% endfor %}
    </div>
  </div>
</section>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    <!-- block content -->
    {% block content %} {% endblock content %}
  </body>
</html>

templates/base_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <!-- block content -->
    {% block content %} {% endblock content %}
  </body>
</html>

templates/components/footer.html
<footer
  class="fixed bottom-0 left-0 right-0 p-4 bg-white shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800"
>
  <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400"
    >© 2022
    <a href="{% url 'main:index' %}" class="hover:underline">DailyNote™</a>. All
    Rights Reserved.
  </span>
</footer>

templates/components/navbar.html
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="relative bg-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div
      class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10"
    >
      <div class="flex justify-start lg:w-0 lg:flex-1">
        <a href="{% url 'main:index' %}">
          <span class="sr-only">DailyNote</span>

          {% if user.is_authenticated %}

          <span class="ml-2 text-lg p-1">User Loggin Is: {{request.user}}</span>
          {% else %}
          <span class="ml-2 text-lg p-1">Daily Note</span>
          {% endif %}
        </a>
      </div>
      <div class="-mr-2 -my-2 md:hidden">
        <button
          type="button"
          class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
          aria-expanded="false"
        >
          <span class="sr-only">Open menu</span>
          <!-- Heroicon name: outline/menu -->
          <svg
            class="h-6 w-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>
        </button>
      </div>

      <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
        {% if user.is_authenticated %}
        <a
          href="{% url 'main:create' %}"
          class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700"
        >
          Create Daily Note
        </a>
        <a
          href="/accounts/logout/"
          class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700"
        >
          Logout
        </a>

        {% endif %}
      </div>
    </div>
  </div>
</div>